#!/usr/bin/env node

/**
 * Import City Pages from Contentful to WordPress
 *
 * Fetches all 820 city pages (pageType: "city") from Contentful,
 * converts rich text to HTML, and creates them as child "community"
 * CPT posts under their parent state in WordPress.
 *
 * Requires: state-contentful-to-wp-map.json (generated by import-states.js)
 *
 * Usage: node src/migration/import-cities.js
 *   Options:
 *     --dry-run     Preview without creating WP posts
 *     --limit=N     Process only first N cities
 *     --offset=N    Skip first N cities
 *     --state=XX    Only import cities for a specific state (e.g. --state=CA)
 */

import 'dotenv/config';
import pkg from 'contentful-management';
const { createClient } = pkg;
import fetch from 'node-fetch';
import https from 'https';
import fs from 'fs';
import path from 'path';
import { richTextToHtml } from '../contentful/rich-text-to-html.js';

// ─── Configuration ───────────────────────────────────────────────────

const contentfulClient = createClient({
  accessToken: process.env.CONTENTFUL_MANAGEMENT_TOKEN,
});

const spaceId = process.env.CONTENTFUL_SPACE_ID || '61iwodu7d9u0';
const envId = process.env.CONTENTFUL_ENVIRONMENT_ID || 'master';

const WP_BASE_URL = process.env.WP_BASE_URL;
const WP_USERNAME = process.env.WP_USERNAME;
const WP_PASSWORD = process.env.WP_APPLICATION_PASSWORD;

const agent = new https.Agent({ rejectUnauthorized: false });
const wpAuth = Buffer.from(`${WP_USERNAME}:${WP_PASSWORD}`).toString('base64');

// ─── CLI Arguments ───────────────────────────────────────────────────

const args = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');
const LIMIT = parseInt(args.find(a => a.startsWith('--limit='))?.split('=')[1]) || 0;
const OFFSET = parseInt(args.find(a => a.startsWith('--offset='))?.split('=')[1]) || 0;
const STATE_FILTER = args.find(a => a.startsWith('--state='))?.split('=')[1]?.toUpperCase() || '';

// ─── Load State Mapping ─────────────────────────────────────────────

const stateMapPath = path.join(process.cwd(), 'out', 'communities', 'state-contentful-to-wp-map.json');
if (!fs.existsSync(stateMapPath)) {
  console.error('❌ State mapping file not found:', stateMapPath);
  console.error('   Run import-states.js first to generate this file.');
  process.exit(1);
}

const stateMap = JSON.parse(fs.readFileSync(stateMapPath, 'utf-8'));
console.log(`📋 Loaded state mapping: ${Object.keys(stateMap).length} states`);

// Build reverse lookup: state abbreviation → WP post ID (for orphan cities)
const stateByAbbr = {};
for (const [contentfulId, info] of Object.entries(stateMap)) {
  stateByAbbr[info.stateShort] = { contentfulId, ...info };
}

// ─── WordPress API Helpers ───────────────────────────────────────────

const RATE_LIMIT_DELAY = 100; // ms between WP requests

async function wpFetch(endpoint, options = {}) {
  const url = `${WP_BASE_URL}/wp-json/wp/v2${endpoint}`;
  const response = await fetch(url, {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Basic ${wpAuth}`,
      ...options.headers,
    },
    agent,
    ...options,
  });
  return response;
}

async function findExistingCommunity(slug) {
  const res = await wpFetch(`/community?slug=${encodeURIComponent(slug)}&status=any&per_page=1`);
  const posts = await res.json();
  if (Array.isArray(posts) && posts.length > 0) {
    return posts[0];
  }
  return null;
}

async function createOrUpdateCommunity(postData) {
  const existing = await findExistingCommunity(postData.slug);

  if (existing) {
    console.log(`   📝 Already exists (ID: ${existing.id}), updating...`);
    const res = await wpFetch(`/community/${existing.id}`, {
      method: 'PUT',
      body: JSON.stringify(postData),
    });

    if (!res.ok) {
      const error = await res.text();
      throw new Error(`Failed to update community: ${error}`);
    }

    const updated = await res.json();
    return { id: updated.id, action: 'updated', url: updated.link };
  }

  // Create new
  const res = await wpFetch('/community', {
    method: 'POST',
    body: JSON.stringify(postData),
  });

  if (!res.ok) {
    const error = await res.text();
    throw new Error(`Failed to create community: ${error}`);
  }

  const created = await res.json();
  return { id: created.id, action: 'created', url: created.link };
}

// ─── Contentful Content Resolution ──────────────────────────────────

function findEntryRefs(node, ids) {
  if (!node) return;
  if (node.data?.target?.sys?.linkType === 'Entry') {
    ids.add(node.data.target.sys.id);
  }
  if (node.content) {
    node.content.forEach(child => findEntryRefs(child, ids));
  }
}

function findAssetRefs(node, ids) {
  if (!node) return;
  if (node.data?.target?.sys?.linkType === 'Asset') {
    ids.add(node.data.target.sys.id);
  }
  if (node.content) {
    node.content.forEach(child => findAssetRefs(child, ids));
  }
}

async function resolveEmbeddedEntries(document, environment) {
  const entries = {};
  const entryIds = new Set();
  findEntryRefs(document, entryIds);

  // Batch-fetch entries in parallel (groups of 10)
  const idArray = [...entryIds];
  const BATCH_SIZE = 10;

  for (let i = 0; i < idArray.length; i += BATCH_SIZE) {
    const batch = idArray.slice(i, i + BATCH_SIZE);
    const results = await Promise.allSettled(
      batch.map(async (entryId) => {
        try {
          const entry = await environment.getEntry(entryId);
          const ct = entry.sys.contentType.sys.id;
          const fields = entry.fields;

          entries[entryId] = {
            contentType: ct,
            title: fields.title?.['en-US'] || fields.name?.['en-US'] || '',
            fields,
          };

          if (ct === 'link') {
            entries[entryId].url = fields.url?.['en-US'] || fields.href?.['en-US'] || '';
            entries[entryId].title = fields.text?.['en-US'] || fields.title?.['en-US'] || fields.label?.['en-US'] || '';
          }

          // Resolve nested linked entries (e.g., linkReference → link entries)
          if (ct === 'linkReference') {
            const links = fields.links?.['en-US'] || [];
            for (const linkRef of links) {
              const linkedId = linkRef?.sys?.id;
              if (linkedId && !entries[linkedId]) {
                try {
                  const linkedEntry = await environment.getEntry(linkedId);
                  const linkedCt = linkedEntry.sys.contentType.sys.id;
                  entries[linkedId] = {
                    contentType: linkedCt,
                    title: linkedEntry.fields.title?.['en-US'] || linkedEntry.fields.linkText?.['en-US'] || '',
                    url: linkedEntry.fields.url?.['en-US'] || '',
                    fields: linkedEntry.fields,
                  };
                } catch (e) {
                  // silently skip
                }
              }
            }
          }

          // Resolve richText embedded body references
          if (ct === 'richText') {
            const nestedBody = fields.body?.['en-US'];
            if (nestedBody?.nodeType === 'document') {
              const nestedIds = new Set();
              findEntryRefs(nestedBody, nestedIds);
              for (const nid of nestedIds) {
                if (!entries[nid]) {
                  try {
                    const ne = await environment.getEntry(nid);
                    entries[nid] = {
                      contentType: ne.sys.contentType.sys.id,
                      title: ne.fields.title?.['en-US'] || ne.fields.name?.['en-US'] || '',
                      fields: ne.fields,
                    };
                  } catch (_) { /* skip */ }
                }
              }
            }
          }
        } catch (error) {
          entries[entryId] = { contentType: 'unknown', title: '', error: error.message };
        }
      })
    );
  }

  return entries;
}

async function resolveEmbeddedAssets(document, environment) {
  const assets = {};
  const assetIds = new Set();
  findAssetRefs(document, assetIds);

  const idArray = [...assetIds];
  const BATCH_SIZE = 10;

  for (let i = 0; i < idArray.length; i += BATCH_SIZE) {
    const batch = idArray.slice(i, i + BATCH_SIZE);
    await Promise.allSettled(
      batch.map(async (assetId) => {
        try {
          const asset = await environment.getAsset(assetId);
          const file = asset.fields.file?.['en-US'];
          assets[assetId] = {
            title: asset.fields.title?.['en-US'] || '',
            description: asset.fields.description?.['en-US'] || '',
            fileName: file?.fileName || '',
            contentType: file?.contentType || '',
            url: file?.url || '',
            width: file?.details?.image?.width,
            height: file?.details?.image?.height,
          };
        } catch (error) {
          assets[assetId] = { title: '', url: '', error: error.message };
        }
      })
    );
  }

  return assets;
}

async function convertRichText(document, environment) {
  if (!document || document.nodeType !== 'document') return { html: '', entryCount: 0, assetCount: 0 };

  const [entries, assets] = await Promise.all([
    resolveEmbeddedEntries(document, environment),
    resolveEmbeddedAssets(document, environment),
  ]);

  const html = richTextToHtml(document, { assets, entries });
  return { html, entryCount: Object.keys(entries).length, assetCount: Object.keys(assets).length };
}

// ─── Slug Helpers ────────────────────────────────────────────────────

/**
 * Convert Contentful city slug to WordPress slug
 * "huntington-wv-facilities" → "huntington-wv"
 * "rosemead-facilities" → "rosemead"
 */
function extractCitySlug(contentfulSlug) {
  return contentfulSlug.replace(/-facilities$/, '');
}

/**
 * Try to extract state abbreviation from city slug or title
 * "huntington-wv" → "WV"
 * "The Best Memory Care Facilities in Huntington, WV" → "WV"
 */
function extractStateAbbrFromCity(slug, title) {
  // Try from slug: last segment might be 2-letter state code
  const slugParts = slug.split('-');
  const lastPart = slugParts[slugParts.length - 1]?.toUpperCase();
  if (lastPart && lastPart.length === 2 && stateByAbbr[lastPart]) {
    return lastPart;
  }

  // Try from title: "... in CityName, XX"
  const titleMatch = title.match(/,\s*([A-Z]{2})\s*$/);
  if (titleMatch && stateByAbbr[titleMatch[1]]) {
    return titleMatch[1];
  }

  return null;
}

/**
 * Resolve the parent state WP post ID for a city entry
 */
function resolveParentState(entry) {
  const parentPageRef = entry.fields.parentPage?.['en-US'];
  const slug = entry.fields.slug?.['en-US'] || '';
  const title = entry.fields.title?.['en-US'] || '';
  const citySlug = extractCitySlug(slug);

  // Method 1: parentPage link → state map
  if (parentPageRef?.sys?.id) {
    const stateInfo = stateMap[parentPageRef.sys.id];
    if (stateInfo) {
      return {
        wpParentId: stateInfo.wpPostId,
        stateShort: stateInfo.stateShort,
        stateName: stateInfo.stateSlug,
        method: 'parentPage',
      };
    }
  }

  // Method 2: Extract state abbreviation from slug/title
  const stateAbbr = extractStateAbbrFromCity(citySlug, title);
  if (stateAbbr && stateByAbbr[stateAbbr]) {
    const info = stateByAbbr[stateAbbr];
    return {
      wpParentId: info.wpPostId,
      stateShort: info.stateShort,
      stateName: info.stateSlug,
      method: 'slug-fallback',
    };
  }

  // Method 3: No parent found — use 0 (top-level)
  return {
    wpParentId: 0,
    stateShort: '',
    stateName: '',
    method: 'orphan',
  };
}

// ─── Main Import Flow ───────────────────────────────────────────────

async function main() {
  console.log('🏙️  Import City Pages: Contentful → WordPress');
  console.log('='.repeat(60));

  if (DRY_RUN) console.log('🔍 DRY RUN MODE — no WordPress changes will be made\n');
  if (LIMIT) console.log(`📏 Limit: ${LIMIT} cities`);
  if (OFFSET) console.log(`⏭️  Offset: starting at city #${OFFSET + 1}`);
  if (STATE_FILTER) console.log(`🗺️  State filter: ${STATE_FILTER} only`);

  // Validate environment
  if (!WP_BASE_URL || !WP_USERNAME || !WP_PASSWORD) {
    console.error('❌ Missing WordPress credentials. Check your .env file.');
    process.exit(1);
  }

  if (!process.env.CONTENTFUL_MANAGEMENT_TOKEN) {
    console.error('❌ Missing CONTENTFUL_MANAGEMENT_TOKEN.');
    process.exit(1);
  }

  // Connect to Contentful
  console.log('\n📡 Connecting to Contentful...');
  const space = await contentfulClient.getSpace(spaceId);
  const environment = await space.getEnvironment(envId);
  console.log('   ✅ Connected');

  // Fetch all city pages
  console.log('\n📥 Fetching city pages from Contentful...');
  const allCityPages = [];
  let skip = 0;
  const limit = 100;

  while (true) {
    const batch = await environment.getEntries({
      content_type: 'page',
      'fields.pageType': 'city',
      limit,
      skip,
    });
    allCityPages.push(...batch.items);
    process.stdout.write(`\r   Fetched ${allCityPages.length}/${batch.total}...`);
    if (allCityPages.length >= batch.total) break;
    skip += limit;
  }
  console.log(`\n   Found ${allCityPages.length} city pages`);

  // Sort by slug for predictable order
  allCityPages.sort((a, b) => {
    const slugA = a.fields.slug?.['en-US'] || '';
    const slugB = b.fields.slug?.['en-US'] || '';
    return slugA.localeCompare(slugB);
  });

  // Apply filters
  let cityPages = allCityPages;

  if (STATE_FILTER) {
    cityPages = cityPages.filter(entry => {
      const parent = resolveParentState(entry);
      return parent.stateShort === STATE_FILTER;
    });
    console.log(`   Filtered to ${cityPages.length} cities in ${STATE_FILTER}`);
  }

  if (OFFSET) {
    cityPages = cityPages.slice(OFFSET);
    console.log(`   After offset: ${cityPages.length} remaining`);
  }

  if (LIMIT) {
    cityPages = cityPages.slice(0, LIMIT);
    console.log(`   After limit: ${cityPages.length} to process`);
  }

  // Deduplicate slugs
  const seenSlugs = new Set();
  const deduped = [];
  for (const entry of cityPages) {
    let citySlug = extractCitySlug(entry.fields.slug?.['en-US'] || '');
    if (seenSlugs.has(citySlug)) {
      citySlug = `${citySlug}-2`;
      console.log(`   ⚠️  Duplicate slug detected, using: ${citySlug}`);
    }
    seenSlugs.add(citySlug);
    entry._wpSlug = citySlug;
    deduped.push(entry);
  }
  cityPages = deduped;

  // Setup output directory
  const outputDir = path.join(process.cwd(), 'out', 'communities', 'cities');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Process each city
  const results = [];
  const startTime = Date.now();

  for (let i = 0; i < cityPages.length; i++) {
    const entry = cityPages[i];
    const fields = entry.fields;
    const contentfulSlug = fields.slug?.['en-US'] || '';
    const title = fields.title?.['en-US'] || '';
    const description = fields.description?.['en-US'] || '';
    const citySlug = entry._wpSlug;
    const linkText = fields.linkText?.['en-US'] || '';
    const heroTextContrast = fields.heroTextContrast?.['en-US'] || false;
    const noindex = fields.noindex?.['en-US'] || false;
    const nofollow = fields.nofollow?.['en-US'] || false;
    const contentBucket = fields.contentBucket?.['en-US'] || '';
    const sitemapGroup = fields.sitemapGroup?.['en-US'] || '';

    // Resolve parent state
    const parentState = resolveParentState(entry);

    // Progress & ETA
    const elapsed = (Date.now() - startTime) / 1000;
    const avgPerCity = i > 0 ? elapsed / i : 0;
    const remaining = (cityPages.length - i) * avgPerCity;
    const eta = remaining > 60 ? `${Math.round(remaining / 60)}m` : `${Math.round(remaining)}s`;

    console.log(`\n${'─'.repeat(60)}`);
    console.log(`[${i + 1}/${cityPages.length}] 🏙️  ${title}`);
    console.log(`   Slug: ${contentfulSlug} → ${citySlug}`);
    console.log(`   Parent: ${parentState.stateShort || 'NONE'} (${parentState.method}) → WP ID ${parentState.wpParentId}`);
    if (i > 0) console.log(`   ⏱️  ETA: ${eta}`);

    try {
      const body = fields.body?.['en-US'];
      const heroContent = fields.heroContent?.['en-US'];

      // Convert hero content
      let heroHtml = '';
      if (heroContent && heroContent.nodeType === 'document') {
        const result = await convertRichText(heroContent, environment);
        heroHtml = result.html;
      }

      // Convert body content
      let bodyHtml = '';
      let entryCount = 0;
      let assetCount = 0;

      if (body && body.nodeType === 'document') {
        const result = await convertRichText(body, environment);
        bodyHtml = result.html;
        entryCount = result.entryCount;
        assetCount = result.assetCount;
        console.log(`   📊 Resolved: ${entryCount} entries, ${assetCount} assets`);
      } else {
        console.log(`   ⚠️  No body content`);
      }

      // Combine content
      let fullContent = '';
      if (heroHtml) {
        fullContent += `<!-- Hero Content -->\n${heroHtml}\n\n<!-- Main Content -->\n`;
      }
      fullContent += bodyHtml;

      // Save HTML preview
      const htmlFilePath = path.join(outputDir, `${citySlug}.html`);
      fs.writeFileSync(htmlFilePath, fullContent);

      if (DRY_RUN) {
        console.log(`   🔍 [DRY RUN] Would create: ${title} under ${parentState.stateShort}`);
        results.push({
          citySlug,
          stateShort: parentState.stateShort,
          title,
          contentfulId: entry.sys.id,
          wpParentId: parentState.wpParentId,
          success: true,
          action: 'dry-run',
          embeddedEntries: entryCount,
          embeddedAssets: assetCount,
        });
        continue;
      }

      // Create WordPress community post
      console.log(`   📤 Sending to WordPress...`);
      const postData = {
        title,
        slug: citySlug,
        content: fullContent,
        status: 'publish',
        parent: parentState.wpParentId,
        excerpt: description,
        meta: {
          contentful_id: entry.sys.id,
          listing_type: 'city',
          state_short: parentState.stateShort,
          state_long: parentState.stateName,
          original_slug: contentfulSlug,
          original_url: `https://www.memorycare.com/${contentfulSlug}/`,
          content_bucket: contentBucket,
          sitemap_group: sitemapGroup,
          link_text: linkText || title.replace(/^The Best Memory Care Facilities in\s*/, ''),
          hero_text_contrast: heroTextContrast,
          noindex,
          nofollow,
        },
      };

      const result = await createOrUpdateCommunity(postData);
      console.log(`   ✅ ${result.action}: ID ${result.id}`);

      results.push({
        citySlug,
        stateShort: parentState.stateShort,
        title,
        contentfulId: entry.sys.id,
        wpPostId: result.id,
        wpParentId: parentState.wpParentId,
        action: result.action,
        success: true,
        embeddedEntries: entryCount,
        embeddedAssets: assetCount,
      });

      // Small delay to avoid overwhelming WP
      await new Promise(r => setTimeout(r, RATE_LIMIT_DELAY));

    } catch (error) {
      console.error(`   ❌ Error: ${error.message}`);
      results.push({
        citySlug,
        stateShort: parentState.stateShort,
        title,
        contentfulId: entry.sys.id,
        success: false,
        error: error.message,
      });
    }
  }

  // ─── Summary ──────────────────────────────────────────────────────

  const totalTime = Math.round((Date.now() - startTime) / 1000);
  console.log(`\n${'='.repeat(60)}`);
  console.log('📊 CITY IMPORT SUMMARY\n');

  const successful = results.filter(r => r.success);
  const failed = results.filter(r => !r.success);
  const orphans = results.filter(r => r.success && !r.stateShort);

  console.log(`✅ Successful: ${successful.length}/${results.length}`);
  console.log(`❌ Failed: ${failed.length}`);
  console.log(`⏱️  Total time: ${Math.floor(totalTime / 60)}m ${totalTime % 60}s`);

  // Per-state breakdown
  const byState = {};
  for (const r of successful) {
    const st = r.stateShort || 'ORPHAN';
    byState[st] = (byState[st] || 0) + 1;
  }
  console.log(`\n📍 Cities per state:`);
  for (const [state, count] of Object.entries(byState).sort((a, b) => a[0].localeCompare(b[0]))) {
    console.log(`   ${state}: ${count}`);
  }

  if (failed.length > 0) {
    console.log(`\n❌ Failed cities:`);
    failed.forEach(r => {
      console.log(`   • ${r.title} (${r.citySlug}): ${r.error}`);
    });
  }

  if (orphans.length > 0) {
    console.log(`\n⚠️  Orphan cities (no parent state):`);
    orphans.forEach(r => {
      console.log(`   • ${r.title} (${r.citySlug})`);
    });
  }

  // Save results
  const resultsPath = path.join(process.cwd(), 'out', 'communities', 'city-import-results.json');
  fs.writeFileSync(resultsPath, JSON.stringify(results, null, 2));
  console.log(`\n💾 Results saved to: ${resultsPath}`);

  // Save city mapping (for potential future use)
  const cityMap = {};
  for (const r of successful) {
    if (r.wpPostId) {
      cityMap[r.contentfulId] = {
        wpPostId: r.wpPostId,
        wpParentId: r.wpParentId,
        citySlug: r.citySlug,
        stateShort: r.stateShort,
        title: r.title,
      };
    }
  }

  const mapPath = path.join(process.cwd(), 'out', 'communities', 'city-contentful-to-wp-map.json');
  fs.writeFileSync(mapPath, JSON.stringify(cityMap, null, 2));
  console.log(`📋 City mapping saved to: ${mapPath}`);

  console.log('\n✨ City import complete!');
}

main().catch(error => {
  console.error('❌ Fatal error:', error.message);
  process.exit(1);
});
